
services:

  snippet-manager:
    container_name: "snippet-manager-infra"
    image: ghcr.io/ingsis-group-9/snippet-manager:7313366b
    environment:
       DB_URL: jdbc:postgresql://snippet-manager-db:5432/snippet-manager
       DB_USERNAME: postgres
       DB_PASSWORD: postgres
    expose:
      - "8083"

  snippet-manager-db:
    container_name: "snippet-manager-infra-db"
    image: postgres
    environment:
      - POSTGRES_DB=snippet-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
