name: "Continuous Deployment"
on:
  push:
    branches:
      - main


jobs:
  update_infra:
    name: Update Infra
    runs-on: ubuntu-latest
    steps:
      - name: Update and Restart Infra
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST_DEV }}
          username: "azureuser"
          key: ${{ secrets.SSH_KEY_PROD }}
          script: |
            cd ~/projects/infra
            docker-compose -f docker-compose.prod.yml stop
            git pull
            docker-compose -f docker-compose.prod.yml up -d --build